language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

addons:
  apt:
    packages:
    - texinfo
    - libgif-dev
    - libxpm-dev

env:
  # Ensure that we build without warnings.
  - CARGO_FLAGS="--features 'strict'"

script:
  # Configure Emacs for building
  - ./autogen.sh
  # --without-makeinfo is only required on OS X.
  # TODO: build info on OS X too.
  - ./configure --without-makeinfo
  - make -j 3

  - make check

notifications:
  fast_finish: true
  email: false

matrix:
  exclude:
    # OS X only builds on nightly, see https://github.com/Wilfred/remacs/pull/112
    - os: osx
      rust: stable
    - os: osx
      rust: beta
    # Don't build nightly on linux, to keep our build quicker.
    - os: linux
      rust: nightly
